# cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_import_id: gh:chrisguest75
    lock_passwd: false
    ssh_authorized_keys:
      - ${SSH_KEY}
packages:
  - nginx
  - docker.io
  - git 
write_files:
  - path : /etc/nginx/conf.d/docker.conf
    content: |
      server {
      listen 80;
      server_name pocketbase.hostml.co;
      
      location / {
        proxy_pass http://localhost:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
  - path: /etc/nginx/sites-available/default


runcmd:
  - apt-get update
  - apt-get upgrade -y
  - sudo git clone git@github.com:kelcheone/pb-docker.git
  - cd pb-docker
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo systemctl enable docker
  - sudo systemctl start docker
  - sudo aa-remove-unknown
  - sudo docker-compose up -d
  - sudo systemctl restart nginx
  - sudo systemctl enable nginx
  - sudo ufw allow 80/tcp
  - sudo ufw allow 443/tcp
  - sudo ufw reload
  - sudo systemctl restart nginx