#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh- authorized-keys:
      - ${SSH_KEY}
packages:
  - nginx
  - python3-pip
  - python3-dev
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-setuptools
  - python3-venv
runcmd:
  - sudo systemctl start nginx
  - sudo systemctl enable nginx
  - sudo ufw allow 'Nginx HTTP'
  - sudo ufw allow 'OpenSSH'
  - sudo ufw enable
  - sudo ufw status
  - sudo mkdir -p /var/www/${DOMAIN_NAME}/html
  - sudo chown -R $USER:$USER /var/www/${DOMAIN_NAME}/html
  - sudo chmod -R 755 /var/www/${DOMAIN_NAME}
  - sudo echo "Hello World" > /var/www/${DOMAIN_NAME}/html/index.html
  - |
    sudo echo "server {
        listen 80;
        listen [::]:80;
        root /var/www/${DOMAIN_NAME}/html;
        index index.html index.htm index.nginx-debian.html;
        server_name ${DOMAIN_NAME} www.${DOMAIN_NAME};
        location / {
            try_files $uri $uri/ =404;
        }
    }" > /etc/nginx/sites-available/${DOMAIN_NAME}
  - sudo ln -s /etc/nginx/sites-available/${DOMAIN_NAME} /etc/nginx/sites-enabled/
  - sudo nginx -t
  - sudo systemctl restart nginx
  - sudo certbot --nginx -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME} --non-interactive --agree-tos --email ${EMAIL}
  - sudo certbot renew --dry-run
  - |
    sudo echo "server {
        listen 80;
        listen [::]:80;
        server_name ${DOMAIN_NAME} www.${DOMAIN_NAME};
        return 301 https://$server_name$request_uri;
    }" > /etc/nginx/sites-available/${DOMAIN_NAME}
  - sudo nginx -t
  - sudo systemctl restart nginx
  - sudo certbot renew --dry-run
  - |
    sudo echo "server {
        listen 443 ssl;
        listen [::]:443 ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;
        root /var/www/${DOMAIN_NAME}/html;
        index index.html index.htm index.nginx-debian.html;
        server_name ${DOMAIN_NAME} www.${DOMAIN_NAME};
        location / {
            try_files $uri $uri/ =404;
        }
    }" > /etc/nginx/sites-available/${DOMAIN_NAME}
  - sudo nginx -t
  - sudo systemctl restart nginx
  - sudo certbot renew --dry-run



#cloud-config
# users:
  # - default
  # - name: terraform
    # gecos: terraform
    # primary_group: hashicorp
    # sudo: ALL=(ALL) NOPASSWD:ALL
    # groups: users, admin
    # ssh_import_id:
    # lock_passwd: false
    # ssh_authorized_keys:
  # - ${SSH_KEY}
# packages:
  # - nginx
  # - docker.io
# 
# runcmd:
  # - apt-get update
  # - apt-get upgrade -y
  # - echo "Hello world" > /var/www/html/index.html
  # - systemctl start nginx
  # - systemctl enable nginx
  # - ufw allow 'Nginx HTTP'
  # - ufw allow 'OpenSSH'
  # - ufw enable
  # 